### PR TITLE
fix: test failure regarding etcd_version variable

### PR DESCRIPTION
**Pull request by Aayush-Abhyarthi**
### Description

https://github.ibm.com/GoldenEye/issues/issues/7101

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — APPROVED** [review]
The solution looks good to me.

The description in the PR needs some work. I think this is an examples only change (nothing in the main module), so it does not require a release.

In addition to this it would be nice to understand what the problem was. The basic example is used in the continuous test (other_test.pr) where a version is passed. Since other_test.pr is already passing a value for etcd_version, the code for the basic example must be updated to accept a value for the continuous test.
This regression was introduced in PR #70 and was not caught in PR testing because basic example only runs in continuous test.

**Comment by ocofaigh** [comment]
The issue is happening because a version of etcd is being passed in the test [here](https://github.com/terraform-ibm-modules/terraform-ibm-icd-etcd/blob/63584efb535d6a39e069d196b841ee1a007ca6c4/tests/other_test.go#L20) but there is no variable for it, so test was failing. I only know that as I looked at the test failure logs. @Aayush-Abhyarthi please include more information in the PR description (or the issue you linked to) so reviewers can have more context when reviewing, thanks.

**Pull request merged**
