### PR TITLE
test: added backup restore from backup id example

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Issue: https://github.ibm.com/GoldenEye/issues/issues/7952

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aashiq-J** [comment]
Screenshot 2024-06-27 at 6 47 14 PM

**Review by iamar7 — DISMISSED** [review]
LGTM

**Review by shemau — CHANGES_REQUESTED** [review]
I am happy with the code and test being similar enough to other ICD instances. From that perspective, good to go.

Was the inclusion of common-dev-assets and oversight. It is not usual to include in feature PR.

**Comment by Aashiq-J** [comment]
@shemau , I have added the etcd database crn in the common-dev-assets `common-permanent-resources.yaml` file, to get this value when running the pr_test had to update the common-dev-assets version in the PR.

**Review by iamar7 — APPROVED** [review]

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
